services:
  hokebo-db:
    image: postgres
    container_name: hokebo-db
    environment:
      - POSTGRES_USER=hokebo-db-admin
      - POSTGRES_PASSWORD=godmodeOhneGod!
      - POSTGRES_DB=hokebo
    ports:
      - 3000:5432
    volumes:
      - hokebo-db-postgres:/var/lib/postgresql/data

volumes:
  hokebo-db-postgres: